name: test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    steps:
      - name: test
        run: echo "test"
